language: go
go:
- 1.9
go_import_path: github.com/ForceCLI/force
before_install:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/mitchellh/gox
script:
- git config --global user.email "you@example.com"
- git config --global user.name "Your Name"
- test -z "$(go fmt)"
- go vet
- go test -v ./...
- go test -v -race ./...
- export OS_TARGETS="darwin windows linux"
- export ARCH_TARGETS="386 amd64"
- export GO_LINKER_VALUE=$(git describe --tags --always)
- export GO_LINKER_SYMBOL="main.Version"
- gox -os "$OS_TARGETS" -arch="$ARCH_TARGETS" -ldflags "-X $GO_LINKER_SYMBOL=$GO_LINKER_VALUE"
- mkdir -p darwin/amd64 && cp force_darwin_amd64 darwin/amd64/force
- mkdir -p darwin/386 && cp force_darwin_386 darwin/386/force
- mkdir -p windows/amd64 && cp force_windows_amd64.exe windows/amd64/force.exe
- mkdir -p windows/386 && cp force_windows_386.exe windows/386/force.exe
- mkdir -p linux/amd64 && cp force_linux_amd64 linux/amd64/force
- mkdir -p linux/386 && cp force_linux_386 linux/386/force
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: W+4pJY7DjLNMU91i3LAOqr6FV+PUnoqCoY1kM9IZ391MCot6EAHkYAdlhSJ2+qllIWmamp7Dtv7Ul4AAfhnAbKJY+J2w5/HczctvjGvcER/QIiWgPfZaNkAqBcWu8XXjdJ876J6sfzWVudK/onnPgpKvtVX0WRZEBXgUl0QJp2g=
  file:
    - force_darwin_amd64
    - force_darwin_386
    - force_linux_amd64
    - force_linux_386
    - force_windows_amd64.exe
    - force_windows_386.exe
  on:
    tags: true
    repo: ForceCLI/force
